apt-get install texlive -y
apt-get install texlive-binaries -y
apt-get install texlive-fonts-recommended -y
apt-get install texlive-generic-recommended -y
apt-get install texlive-latex-base -y
apt-get install texlive-latex-extra -y
apt-get install texlive-latex-recommended -y
apt-get install texlive-pictures -y
apt-get install latexmk -y
apt-get install python-pygments -y
apt-get install evince -y
